# railway.toml

[build]
builder = "NIXPACKS"
buildCommand = "bun install && bun run build"

[services.backend]
root = "apps/backend"
start = "bun run start"

[services.frontend]
root = "apps/frontend"
build = "bun run build"
start = "bun run start"
